#log level
logging:
 level:
  root: debug

spring:
 datasource: 
  url: jdbc:sqlite:/data/nostr/relay.db
  driver-class-name: org.sqlite.JDBC
  # username: 选用 sqlite 数据库不需要配置此项
  # password: 选用 sqlite 数据库不需要配置此项
 sql:
  init:
   schema-locations: classpath:db/schema.sql
   mode: always

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.leafbodhi.nostr.model